//
//  LoginInteractor.swift
//  InvestScopio
//
//  Created by Joao Medeiros Pereira on 12/06/19.
//  Copyright (c) 2019 Joao Medeiros Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol INVSResendPasswordInteractorProtocol {
    func checkToolbarAction(withTextField textField: INVSFloatingTextField, typeOfAction type: INVSKeyboardToolbarButton)
    func resendPassword()
    var allTextFields: [INVSFloatingTextField] { get }
}

class INVSResendPasswordInteractor: INVSResendPasswordInteractorProtocol {
    var presenter: INVSResendPasswordPresenterProtocol?
    var worker: INVSResendPasswordWorkerProtocol = INVSResendPasswordWorker()
    var allTextFields = [INVSFloatingTextField]()
  // MARK: Do something
  
    func checkToolbarAction(withTextField textField: INVSFloatingTextField, typeOfAction type: INVSKeyboardToolbarButton) {
        presenter?.presentToolbarAction(withPreviousTextField: textField, allTextFields: allTextFields, typeOfAction: type)
    }
    
    func resendPassword() {
        worker.resendPassword(withTextFields: allTextFields, successCompletionHandler: { (email, title, message, shouldHideAutomatically, popupType) in
            self.presenter?.presentSuccessResendPassword(withEmail: email, title: title, message: message, shouldHideAutomatically: shouldHideAutomatically, popupType: popupType)
        }, errorCompletionHandler: { (title, message, shouldHideAutomatically, popupType) in
            self.presenter?.presentErrorResendPassword(titleError: title, messageError: message, shouldHideAutomatically: shouldHideAutomatically, popupType: popupType)
        })
    }
}
