//
//  INVSInterestRatePresenter.swift
//  InvestScopio
//
//  Created by Joao Medeiros Pereira on 26/08/19.
//  Copyright (c) 2019 Joao Medeiros Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol INVSInterestRatePresenterProtocol {
    func presentChangeType(index: Int)
}

class INVSInterestRatePresenter: INVSInterestRatePresenterProtocol {
   
    weak var viewController: INVSInterestRateViewControllerProtocol?
  
    func presentChangeType(index: Int) {
        let type = INVSInterestRateType(rawValue: index) ?? .monthly
        viewController?.displayChangeType(type: type)
            
     }
     
}
