//
//  INVSInterestRateInteractor.swift
//  InvestScopio
//
//  Created by Joao Medeiros Pereira on 26/08/19.
//  Copyright (c) 2019 Joao Medeiros Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol INVSInterestRateInteractorProtocol {
    func changeType(index: Int)
    var interestRateValue: String? { get set }
    var interestRateType: INVSInterestRateType? { get set }
}


class INVSInterestRateInteractor: INVSInterestRateInteractorProtocol {
    
    var presenter: INVSInterestRatePresenterProtocol?
    var worker: INVSInterestRateWorkerProtocol = INVSInterestRateWorker()
    var interestRateValue: String? = ""
    var interestRateType: INVSInterestRateType? = .monthly
    func changeType(index: Int) {
        presenter?.presentChangeType(index: index)
    }

}
