//
//  LoginWorker.swift
//  InvestScopio
//
//  Created by Joao Medeiros Pereira on 12/06/19.
//  Copyright (c) 2019 Joao Medeiros Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

typealias PopMessageInfo = (title: String, message: String)
typealias SuccessSignUpHandler = (_ email:String, _ title:String,_ message:String, _ shouldHideAutomatically:Bool, _ popupType:INVSPopupMessageType) -> ()
typealias ErrorSignUpHandler = (_ titleError:String,_ messageError:String, _ shouldHideAutomatically:Bool, _ popupType:INVSPopupMessageType) ->()

protocol INVSSignUpWorkerProtocol {
    func signUp(withTextFields textFields: [INVSFloatingTextField], successCompletionHandler: @escaping(SuccessSignUpHandler), errorCompletionHandler:@escaping(ErrorSignUpHandler))
}

class INVSSignUpWorker: NSObject,INVSSignUpWorkerProtocol {
    func signUp(withTextFields textFields: [INVSFloatingTextField], successCompletionHandler: @escaping(SuccessSignUpHandler), errorCompletionHandler:@escaping(ErrorSignUpHandler)) {
        if let textFieldsError = check(withTextFields: textFields) {
            errorCompletionHandler(textFieldsError.title, textFieldsError.message, true, .error)
            return
        }
        if let email = textFields.filter({$0.typeTextField == .email}).first?.floatingTextField.text?.lowercased(), let password = textFields.filter({$0.typeTextField == .confirmPassword}).first?.floatingTextField.text {
            Auth.auth().createUser(withEmail: email, password: password) { (result, error) in
                guard result != nil else {
                    if let error = error {
                        if let firebaseErrorHandler = FireBaseErrorHandler.init(rawValue: error._code)?.getFirebaseError() {
                            errorCompletionHandler(firebaseErrorHandler.titleError, firebaseErrorHandler.messageError, firebaseErrorHandler.shouldHideAutomatically, firebaseErrorHandler.popupType)
                         return
                        }
                    }
                    errorCompletionHandler(INVSFloatingTextFieldType.defaultTitle(), INVSFloatingTextFieldType.defaultMessage(), true, .error)
                        
                    return
                }
                successCompletionHandler(email, "Finalizado.\n", "Seu cadastro foi realizado com sucesso!\nVerifique seu email para ativa-lo.", true, .alert)
                return
            }
        }
    }
    private func check(withTextFields textFields:[INVSFloatingTextField]) -> PopMessageInfo? {
        if let emailTextField = textFields.filter({$0.typeTextField == .email}).first {
            if emailTextField.floatingTextField.text?.isValidEmail() == false {
                if emailTextField.required {
                    emailTextField.hasError = true
                    emailTextField.floatingTextField.becomeFirstResponder()
                }
                return PopMessageInfo(title: emailTextField.typeTextField?.getTitleMessageInfo() ?? "", message: emailTextField.typeTextField?.getMessageInfo() ?? "")
            }
            emailTextField.hasError = false
        }
        if let passwordTextField = textFields.filter({$0.typeTextField == .password}).first, let confirmPasswordTextField = textFields.filter({$0.typeTextField == .confirmPassword}).first {
            if passwordTextField.floatingTextField.text != confirmPasswordTextField.floatingTextField.text {
                passwordTextField.hasError = true
                passwordTextField.floatingTextField.becomeFirstResponder()
                confirmPasswordTextField.hasError = true
                return PopMessageInfo(title: confirmPasswordTextField.typeTextField?.getTitleMessageInfo() ?? "", message: confirmPasswordTextField.typeTextField?.getMessageInfo() ?? "")
            }
            passwordTextField.hasError = false
            confirmPasswordTextField.hasError = false
        }
        return nil
    }
}
