//
//  LoginPresenter.swift
//  InvestScopio
//
//  Created by Joao Medeiros Pereira on 12/06/19.
//  Copyright (c) 2019 Joao Medeiros Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol INVSSignUpPresenterProtocol {
    func presentToolbarAction(withPreviousTextField textField: INVSFloatingTextField, allTextFields textFields: [INVSFloatingTextField], typeOfAction type: INVSKeyboardToolbarButton)
    func presentSuccessSignUp(withEmail email:String, title:String, message:String, shouldHideAutomatically:Bool, popupType:INVSPopupMessageType)
    func presentErrorSignUp(titleError:String, messageError:String, shouldHideAutomatically:Bool, popupType:INVSPopupMessageType)
    
}

class INVSSignUpPresenter: INVSSignUpPresenterProtocol {
    weak var viewController: INVSSignUpViewControllerProtocol?
  
    func presentToolbarAction(withPreviousTextField textField: INVSFloatingTextField, allTextFields textFields: [INVSFloatingTextField], typeOfAction type: INVSKeyboardToolbarButton) {
        switch type {
        case .back:
            break
        case .cancel:
            viewController?.displayCancelAction()
        case .ok:
            let nextTextField = textField.typeTextField?.getNext(allTextFields: textFields)
            viewController?.displayOkAction(withTextField: nextTextField ?? textField, andShouldResign: nextTextField == nil)
        }
    }
    
    func presentSuccessSignUp(withEmail email:String, title:String, message:String, shouldHideAutomatically:Bool, popupType:INVSPopupMessageType) {
        viewController?.displaySignUpSuccess(withEmail: email, title: title, message: message, shouldHideAutomatically: shouldHideAutomatically, popupType: popupType)
    }
    func presentErrorSignUp(titleError:String, messageError:String, shouldHideAutomatically:Bool, popupType:INVSPopupMessageType) {
        viewController?.displaySignUpError(titleError: titleError, messageError: messageError, shouldHideAutomatically: shouldHideAutomatically, popupType: popupType)
        
    }
    
}
